'use client';
import { Activity, BarChart3, KeyRound, MessageCircle, RefreshCw, Send, ServerCog, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { getAdminLogs, getAdminQueryStats, getAdminStats, getWhatsAppConfigStatus, sendWhatsAppAlert } from '@/lib/plantbrain-api';
type Data = Record<string, any>;
export function AdminConsolePanel({ onComplete }: { onComplete: () => void }) {
 const [key,setKey]=useState(''); const [stats,setStats]=useState<Data|null>(null); const [queries,setQueries]=useState<Data|null>(null); const [logs,setLogs]=useState<string[]>([]); const [wa,setWa]=useState<Data|null>(null); const [to,setTo]=useState(''); const [message,setMessage]=useState('PlantBrain test alert: integration is operational.'); const [status,setStatus]=useState(''); const [loading,setLoading]=useState(false);
 const refresh=async()=>{setLoading(true);setStatus('');try{const [s,q,l,w]=await Promise.all([getAdminStats(key),getAdminQueryStats(key),getAdminLogs(key),getWhatsAppConfigStatus()]);setStats(s);setQueries(q);setLogs(l.lines||[]);setWa(w);onComplete();}catch(e:any){setStatus(e?.message||'Admin request failed');}finally{setLoading(false)}};
 const send=async()=>{if(!to.trim())return setStatus('Enter your WhatsApp number including country code.');setLoading(true);try{const r=await sendWhatsAppAlert(to.trim(),message);setStatus(`Alert ${r.status}. Message SID: ${r.message_sid}`);}catch(e:any){setStatus(e?.message||'WhatsApp alert failed');}finally{setLoading(false)}};
 const db=stats?.database||{};
 return <div className="space-y-5"><section className="border border-white/10 bg-white/[0.04] p-5"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><div className="text-xs font-semibold uppercase tracking-[0.2em] text-rose-300">Platform administration</div><h2 className="mt-2 text-2xl font-semibold">System control center</h2><p className="mt-2 text-sm text-slate-400">Runtime health, usage, integrations, and protected operational data.</p></div><div className="flex w-full gap-2 md:w-auto"><label className="flex min-w-64 items-center gap-2 border border-white/10 bg-black/20 px-3"><KeyRound className="h-4 w-4 text-slate-500"/><input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="ADMIN_API_KEY" className="w-full bg-transparent py-2 text-sm outline-none"/></label><button onClick={refresh} disabled={loading} className="bg-rose-400 px-3 text-slate-950"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div></div>{status&&<div className="mt-4 border border-amber-400/20 bg-amber-400/10 p-3 text-sm text-amber-100">{status}</div>}</section>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={ServerCog} label="Documents" value={db.documents?.total??'-'}/><Metric icon={Activity} label="Equipment" value={db.equipment??'-'}/><Metric icon={ShieldCheck} label="Rules" value={db.compliance_rules??'-'}/><Metric icon={BarChart3} label="Queries" value={queries?.queries_all_time??'-'}/></div>
 <div className="grid gap-5 xl:grid-cols-2"><section className="border border-white/10 bg-white/[0.04] p-5"><div className="flex items-center gap-2 font-semibold"><MessageCircle className="h-5 w-5 text-emerald-300"/>WhatsApp integration</div><div className="mt-4 flex items-center justify-between border border-white/10 bg-black/20 p-3 text-sm"><span>Twilio configuration</span><span className={wa?.configured?'text-emerald-300':'text-amber-300'}>{wa?wa.configured?'Ready':'Needs .env values':'Check status'}</span></div><input value={to} onChange={e=>setTo(e.target.value)} placeholder="Your number, e.g. whatsapp:+919876543210" className="mt-3 w-full border border-white/10 bg-black/20 px-3 py-3 text-sm outline-none"/><textarea value={message} onChange={e=>setMessage(e.target.value)} className="mt-3 min-h-24 w-full border border-white/10 bg-black/20 p-3 text-sm outline-none"/><button onClick={send} disabled={loading||!wa?.configured} className="mt-3 inline-flex items-center gap-2 bg-emerald-400 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-40"><Send className="h-4 w-4"/>Send test alert</button></section>
 <section className="border border-white/10 bg-white/[0.04] p-5"><h3 className="font-semibold">Recent backend logs</h3><div className="mt-4 max-h-64 overflow-auto bg-black/30 p-3 font-mono text-[11px] leading-5 text-slate-400">{logs.length?logs.slice(-30).map((line,i)=><div key={i}>{line}</div>):'Load admin data to inspect runtime logs.'}</div></section></div></div>;
}
function Metric({icon:Icon,label,value}:{icon:React.ComponentType<{className?:string}>;label:string;value:React.ReactNode}){return <div className="border border-white/10 bg-white/[0.04] p-4"><Icon className="h-5 w-5 text-cyan-300"/><div className="mt-4 text-2xl font-semibold">{value}</div><div className="mt-1 text-xs uppercase tracking-[0.14em] text-slate-500">{label}</div></div>}
