'use client';
import { ArrowRight, ClipboardList, Gauge, ShieldAlert, Sparkles, Wrench } from 'lucide-react';
import type { DemoStep } from './DemoShell'; import type { PlantRole } from './RoleSelect'; import { roleNames } from './RoleSelect';
export function OperationsOverview({ role, onNavigate }: { role: PlantRole; onNavigate: (step: DemoStep) => void }) { return <div className="space-y-5">
<section className="border-l-4 border-l-red-500 bg-[#151510] p-5 shadow-xl"><div className="text-xs font-semibold uppercase tracking-[0.16em] text-[#b9a78e]">Today&apos;s priority | {roleNames[role]}</div><h2 className="mt-2 text-xl font-semibold text-white">Main Turbine T-402 - bearing failure likely in 11 days</h2><p className="mt-2 text-sm text-[#bdad97]">PlantBrain analysed inspection history and recommends immediate action.</p><button onClick={() => onNavigate('ask')} className="mt-5 inline-flex items-center gap-2 bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><Sparkles className="h-4 w-4" /> Review AI recommendation</button></section>
<div className="grid grid-cols-3 gap-3">{[['3','Critical','text-red-400 bg-red-500/10'],['4','Warnings','text-amber-400 bg-amber-500/10'],['4','Healthy','text-emerald-400 bg-emerald-500/10']].map(([v,l,s]) => <div key={l} className={`p-4 text-center ${s}`}><div className="text-3xl font-bold">{v}</div><div className="mt-1 text-xs font-semibold uppercase">{l}</div></div>)}</div>
<section className="border border-white/10 bg-[#12130f] p-5"><div className="flex items-center justify-between"><div><div className="text-xs uppercase tracking-[0.18em] text-[#8f8069]">Overall equipment effectiveness</div><div className="mt-2"><span className="text-5xl font-bold text-white">87</span><span className="ml-2 text-sm text-[#a99982]">% OEE</span></div></div><Gauge className="h-14 w-14 text-cyan-400" /></div><div className="mt-6 space-y-3">{[['Availability','94.8%','w-[95%]'],['Performance','91.2%','w-[91%]'],['Quality','98.5%','w-[98%]']].map(([l,v,w]) => <div key={l}><div className="mb-1 flex justify-between text-sm"><span>{l}</span><span className="text-cyan-300">{v}</span></div><div className="h-2 bg-white/5"><div className={`h-full bg-cyan-400 ${w}`} /></div></div>)}</div></section>
<div className="grid gap-3 md:grid-cols-3"><Action icon={ClipboardList} title="Plant documents" copy="Load demo PDF or upload field records" onClick={() => onNavigate('documents')} /><Action icon={Wrench} title="Ask PlantBrain" copy="Get cited maintenance guidance" onClick={() => onNavigate('ask')} /><Action icon={ShieldAlert} title="Failure intelligence" copy="Warnings from incidents, QMS gaps, and graph context" onClick={() => onNavigate('risk')} /></div></div>; }
function Action({ icon: Icon, title, copy, onClick }: { icon: React.ComponentType<{ className?: string }>; title: string; copy: string; onClick: () => void }) { return <button onClick={onClick} className="border border-white/10 bg-white/[0.03] p-4 text-left hover:border-cyan-400/40"><Icon className="h-5 w-5 text-cyan-300" /><span className="mt-4 block font-semibold text-white">{title}</span><span className="mt-1 block text-xs text-slate-400">{copy}</span><ArrowRight className="mt-4 h-4 w-4" /></button>; }
